stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH
  # IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:cipsko

.docker_login:
  before_script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image_staging:
  extends: .docker_login
  stage: build
  tags:
    - linux
  script:
    - docker image prune -f
    - docker container prune -f
    - docker build -t $IMAGE_TAG:$CI_COMMIT_SHORT_SHA frontend
    - docker tag $IMAGE_TAG:$CI_COMMIT_SHORT_SHA $IMAGE_TAG:latest
    - docker push $IMAGE_TAG:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_TAG:latest
  except:
    - prod

build_image_prod:
  extends: .docker_login
  stage: build
  tags:
    - linux
  script:
    - docker image prune -f
    - docker container prune -f
    - docker build -t $IMAGE_TAG:$CI_COMMIT_SHORT_SHA --build-arg REACT_APP_MANHATTAN_API_URL=http://api.manhattan.trejdoo.com/v1 frontend
    - docker tag $IMAGE_TAG:$CI_COMMIT_SHORT_SHA $IMAGE_TAG:prod
    - docker push $IMAGE_TAG:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_TAG:prod
  only:
    - prod

deploy_staging:
  stage: deploy
  tags:
   - kube-master-staging
  script:
   - echo $IMAGE_TAG
   - kubectl delete -f deployment/uat/pod.yml || echo cannot delete such pod
   - kubectl apply -f deployment/uat/pod.yml
   
   - kubectl delete -f deployment/uat/service.yml || echo cannot delete such service
   - kubectl apply -f deployment/uat/service.yml

   - kubectl delete -f deployment/uat/ingress.yml || echo cannot delete such ingress
   - kubectl apply -f deployment/uat/ingress.yml

  environment:
    name: staging
    url: https://uat.dashboard.manhattan.trejdoo.com
  except:
    - prod


deploy_prod:
  stage: deploy
  tags:
   - kube-master-prod
  script:
   - echo $IMAGE_TAG
   - kubectl delete -f deployment/prod/pod.yml || echo cannot delete such pod
   - kubectl apply -f deployment/prod/pod.yml
   
   - kubectl delete -f deployment/prod/service.yml || echo cannot delete such service
   - kubectl apply -f deployment/prod/service.yml

   - kubectl delete -f deployment/prod/ingress.yml || echo cannot delete such ingress
   - kubectl apply -f deployment/prod/ingress.yml

  environment:
    name: staging
    url: https://dashboard.manhattan.trejdoo.com
  only:
    - prod

